name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    # we want to run on forks but avoid duplicates inside our own repo
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'krzkaczor/earl'
    
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.2.0'

      - name: Cache YARN dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-

      - name: Install
        run: yarn --no-progress --non-interactive --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Prettier
        run: yarn format

      - name: Test
        run: CI=true yarn test

      - name: Typecheck
        run: yarn typecheck
# Few tips github actions
# - name: Setup SSH debug session
#   uses: mxschmitt/action-tmate@v2

