# ew tips github actions
# -#   uses: mxschmitt/action-tmate@v2
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  CI:
    strategy:
      matrix:
        node: ["16.x", "18.x"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm format
      - run: pnpm test
      - run: pnpm typecheck
