name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  CI:
    strategy:
      matrix:
        node: ['12.x', '14.x', '16.x']
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache YARN dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.OS }}-${{ matrix.node }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-${{ matrix.node }}-yarn-cache-

      - name: Install
        run: yarn --no-progress --non-interactive --frozen-lockfile --ignore-optional

      - name: Lint
        run: yarn lint

      - name: Prettier
        run: yarn format

      - name: Build (excluding website)
        run: yarn build

      - name: Test
        run: yarn test

      - name: Typecheck
        run: yarn typecheck

  test-docs:
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache YARN dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.OS }}-${{ matrix.node }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-${{ matrix.node }}-yarn-cache-

      - name: Install
        run: yarn --no-progress --non-interactive --frozen-lockfile --ignore-optional

      - name: Build (excluding website)
        run: yarn build

      - name: Generate api-reference
        run: |
          cd packages/website
          yarn api-reference

# Few tips github actions
# - name: Setup SSH debug session
#   uses: mxschmitt/action-tmate@v2

