name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Either creates release PR or releases everything (packages to npm, documentation do netlify)
        uses: changesets/action@master
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN2 }}
          NETLIFY_APP_ID: ${{ secrets.NETLIFY_APP_ID }}
          NETLIFY_API_KEY: ${{ secrets.NETLIFY_API_KEY }}
