name: Release (canary)

on:
  push:
    branches:
      - master
    paths:
      - 'packages/earl/**'
      - '.github/workflows/release-canary.yml'

jobs:
  release-canary:
    name: Release (canary)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm build:earl

      - name: Set version
        run: |
          pnpm changeset version
          
          cd packages/earl
          npm pkg set version=$(npm pkg get version | jq .earl -r)-canary.$(date +'%Y%m%dT%H%M%S')
          echo "Version changed: $(npm pkg get version)"

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          package: packages/earl/package.json
          token: ${{ secrets.NPM_TOKEN2 }}
          dry-run: false
          tag: canary
