name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Either creates release PR or publishes packages to npm
        id: changesets
        uses: changesets/action@master
        with:
          version: pnpm changeset:version
          publish: pnpm changeset:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN2 }}
        
      - name: Push docs if a publish happens
        if: steps.changesets.outputs.published == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          branch: docs-stable
